# Generated by Django 4.0.5 on 2023-02-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Metadados',
            new_name='Metadado',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='metadados',
            new_name='metadado',
        ),
        migrations.RenameField(
            model_name='uf',
            old_name='metadados',
            new_name='metadado',
        ),
    ]
